apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: spring-helloworld-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: spring-helloworld
spec:
  replicas: 1
  selector:
    app: spring-helloworld
  template:
    metadata:
      labels:
        app: spring-helloworld
    spec:
      containers:
      - name: spring-helloworld-container
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.container.port }}
          protocol: TCP
  triggers:
  - type: ConfigChange

