apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: spring-helloworld-deployment
  labels:
    app: spring-helloworld
spec:
  replicas: 1
  selector:
    app: spring-helloworld
  template:
    metadata:
      labels:
        app: spring-helloworld
    spec:
      containers:
      - name: spring-helloworld-container
        image: quay.io/redhat_emp1/spring-helloworld:1693317657117
        ports:
        - containerPort: 8080
          protocol: TCP
  triggers:
  - type: ConfigChange

