kind: Secret
apiVersion: v1
metadata:
  name: docker-credentials
  namespace: esercito-tekton
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJxdWF5LmlvIjp7InVzZXJuYW1lIjoiZHNjcmltaWUiLCJwYXNzd29yZCI6IlZpYWFyb25hODIhIiwiYXV0aCI6IlpITmpjbWx0YVdVNlZtbGhZWEp2Ym1FNE1pRT0ifX19
type: kubernetes.io/dockerconfigjson

