apiVersion: v1
kind: Service
metadata:
  name: spring-helloworld-service
  namespace: {{ .Values.namespace }}
  labels:
    app: spring-helloworld
spec:
  selector:
    app: spring-helloworld
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}

